server:
  port: 8000
  servlet:
    context-path: /
spring:
  datasource:
        #引入druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/jtdb?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true
    username: root
    password: Ghx01211202
  #配置视图解析器
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
      
  #定义服务名称(必须定义)    
  application:    name: provider-user
    
eureka:  client:    service-url:      defaultZone:  http://localhost:7000/eureka
  instance:
    #多个服务id不同    instance-id: provider-user-8000
    #是否显示IP和端口
    prefer-ip-address: true
   
    
#mybatis-plush配置
mybatis-plus:
  type-aliases-package: com.jt.springcloud.pojo
  mapper-locations: classpath:/mybatis/mappers/*.xml
  configuration:
  #驼峰映射
    map-underscore-to-camel-case: true

logging:
  level: 
    com.jt.mapper: debug